- hosts: localhost
  connection: local

  vars:
    region: eu-west-1
    ami: ami-c39604b0
    env: p
    ipcode: P386
    system_code: 'Video-Platform'
    description: 'Video Platform Cluster Specific'
    team_dl: videyo@ft.com
    environment_tag: default
    master_instance_type: c4.xlarge
    general_instance_type: t2.medium
    smaller_instance_type: t2.small
    docker_volume_size: 20

  tasks:
    - name: Create buckets
      s3_bucket:
        name: "mio-{{item}}-{{clusterid}}"
        region: "{{region}}"
      with_items:
        - raw
        - edit
        - raw-proxy
        - edit-proxy
        - audio
        - web-video

    - name: Build master instance one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
          - "{{cloudamqp_security_group_id}}"
          - "{{elasticsearch_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}01-law1a-eu-{{env}}"
        instance_type: "{{master_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}01-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "master"
          cluster: "{{clusterid}}"
          description: "{{description}} master box"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build master instance two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
          - "{{cloudamqp_security_group_id}}"
          - "{{elasticsearch_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}02-law1a-eu-{{env}}"
        instance_type: "{{master_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}02-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "master"
          cluster: "{{clusterid}}"
          description: "{{description}} master box"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build job instance one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
          - "{{cloudamqp_security_group_id}}"
          - "{{elasticsearch_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}03-law1a-eu-{{env}}"
        instance_type: "{{general_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}03-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "job"
          cluster: "{{clusterid}}"
          description: "{{description}} job box"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build job instance two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
          - "{{cloudamqp_security_group_id}}"
          - "{{elasticsearch_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}04-law1a-eu-{{env}}"
        instance_type: "{{general_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}04-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "job"
          cluster: "{{clusterid}}"
          description: "{{description}} job box"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build services instance
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
          - "{{cloudamqp_security_group_id}}"
          - "{{elasticsearch_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}05-law1a-eu-{{env}}"
        instance_type: "{{general_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}05-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "service"
          cluster: "{{clusterid}}"
          description: "{{description}} services box"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build utilities instance
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
          - "{{cloudamqp_security_group_id}}"
          - "{{elasticsearch_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}06-law1a-eu-{{env}}"
        instance_type: "{{general_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}06-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "utility"
          cluster: "{{clusterid}}"
          description: "{{description}} utilities box"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)


    - name: Build router one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{web_security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{public_subnet_0}}"
        assign_public_ip: yes
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}07-law1a-eu-{{env}}"
        instance_type: "{{smaller_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}07-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "router"
          cluster: "{{clusterid}}"
          description: "{{description}} router"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build router two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{web_security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{public_subnet_1}}"
        assign_public_ip: yes
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}08-law1a-eu-{{env}}"
        instance_type: "{{smaller_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}08-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "router"
          cluster: "{{clusterid}}"
          description: "{{description}} router"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build consul one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}09-law1a-eu-{{env}}"
        instance_type: "{{smaller_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}09-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "consul"
          cluster: "{{clusterid}}"
          description: "{{description}} consul"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build consul two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}10-law1a-eu-{{env}}"
        instance_type: "{{smaller_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}10-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "consul"
          cluster: "{{clusterid}}"
          description: "{{description}} consul"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)

    - name: Build consul three
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}11-law1a-eu-{{env}}"
        instance_type: "{{smaller_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}11-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "consul"
          cluster: "{{clusterid}}"
          description: "{{description}} consul"
        volumes:
          - device_name: /dev/xvdg
            volume_type: gp2
            volume_size: "{{docker_volume_size}}"
            delete_on_termination: true
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

          [ -f /dev/xvdg1 ] || ( parted -a optimal --script /dev/xvdg 'mklabel gpt mkpart P1 1 -0' && mkfs.ext4 /dev/xvdg1)
