- hosts: localhost
  connection: local

  vars:
    region: eu-west-1
    ami: ami-c39604b0
    env: p
    ipcode: P386
    system_code: 'Video-Platform'
    description: 'Video Platform Cluster Specific'
    team_dl: videyo@ft.com
    environment_tag: default
    storage_instance_type: m3.medium
    instance_type: m4.large
    short_name: mio

  tasks:
    - name: Create buckets
      s3_bucket:
        name: "mio-{{item}}-{{clusterid}}"
        region: "{{region}}"
      with_items:
        - raw
        - edit
        - raw-proxy
        - edit-proxy
        - audio
        - web-video

    - name: Build mio in a box instance
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "ftflex{{clusterid}}01-law1a-eu-{{env}}"
        instance_type: "{{instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftflex{{clusterid}}01-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "master"
          cluster: "{{clusterid}}"
          description: "{{description}} master box"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh
