- hosts: storage
  become: yes
  vars:
    clusterid: test

  tasks:
    - name: create export dirs
      file:
        path: "/{{clusterid}}/{{item}}"
        state: directory
        mode: 0755
        recurse: yes
      with_items:
        - u01
        - u02

    - name: export dirs
      lineinfile:
        dest: /etc/exports
        create: yes
        line: "/{{clusterid}}/{{item}} *(rw,no_root_squash,sync)"
      with_items:
        - u01
        - u02

    - name: grab down jars
      shell: aws s3 cp --recursive --region eu-west-1 "s3://com.ft.video.artefacts/jars/{{ jar_version }}/" .
      args:
        chdir: "/{{clusterid}}/u01"

    - name: exportfs
      shell: exportfs -a

- hosts:
  - master
  become: yes
  vars:
    clusterid: test

  tasks:
    - name: install nfs client
      yum:
        name: nfs-utils
        state: latest

    - name: create /stuff
      file:
        path: /stuff
        state: directory
        mode: 0755


    - name: mount storage u01
      mount:
        fstype: nfs4
        src: "{{ hostvars[groups['storage'][0]]['ansible_eth0']['ipv4']['address'] }}:/{{clusterid}}/u01"
        name: /stuff
        state: mounted

    - name: hosts file magic
      shell: "echo -e $(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')\t\t$(hostname) >> /etc/hosts"

    - name: fix path
      lineinfile:
        dest: /etc/profile
        create: yes
        line: "export PATH=/usr/local/bin:$PATH"

    - name: install docker
      yum:
        name: docker
        state: latest

    - name: enable docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: install pip deps
      pip:
        executable: pip-2.7  
        name: "{{item}}"
      with_items:
        - docker-compose

    - name: hard lock docker-py for ansible bug
      pip:
        name: docker-py
        version: 1.9.0

    - name: login to ooyala repo
      docker_login:
        username: ft
        password: "{{ooyala_password}}"
        registry: registry.ooflex.net

    - name: start consul container
      docker_container:
        name: consul
        image: registry.ooflex.net/consul:latest
        published_ports:
          - "8300:8300"
          - "8301:8301"
          - "8301:8301/udp"
          - "8302:8302"
          - "8400:8400"
          - "8500:8500"
          - "53:8600/udp"
        env:
          IP: 172.17.0.1
          SERVICE_IGNORE: true
        volumes:
          - /stuff/consul:/flex/consul

    - name: configure database
      docker_container:
        name: flex-data
        image: quay.io/financialtimes/flex-data
        env:
          DB_HOST: "{{db_host}}"
          DB_MASTERUSERNAME: "{{db_masterusername}}"
          MONGO_MASTERUSERNAME: "{{ mongo_masterusername }}"
          DB_MASTERPASSWORD: "{{db_masterpassword}}"
          MONGO_MASTERPASSWORD: "{{ mongo_masterpassword }}"
          DB_PASSWORD: "{{db_password}}"
          CLUSTER_ID: "{{clusterid}}"
          MONGO_HOST: "{{ single_mongo_host }}"

- hosts: localhost
  connection: local
  vars:
    consul: localhost:8500
    clusterid: test
    domain: "flex-{{clusterid}}.ft.com"

  tasks:
    - name: configure consul stuff
      shell: /tool/configure_consul

- hosts: localhost
  connection: local
  tasks:
    - name: create docker-compose
      shell: cat 00-base.yml services-*.yml utility-*.yml master-*.yml > ../docker-compose.yml
      args:
        chdir: /playbooks/templates/docker-compose-components
      ignore_errors: yes

- hosts: master
  become: yes
  tasks:
    - name: set monitoreador name
      lineinfile:
        dest: /etc/monitoreador.env
        create: yes
        line: "export SYSTEM_NAME='flex {{clusterid}} sole node'"

    - name: generate docker-compose
      template:
        src: ../../templates/docker-compose.yml
        dest: /root/docker-compose.yml

# Seriously... what the shit?

    - name: docker-compose pull down
      shell: curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose

    - name: make executable
      shell: chmod +x /usr/bin/docker-compose

    - name: start containers
      shell: docker-compose -f /root/docker-compose.yml up -d

    - name: start registrator
      docker_container:
        name: registrator
        image: registry.ooflex.net/registrator
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock
        env:
          IP: "{{ ansible_default_ipv4.address }}"

    - name: start annihilator
      docker_container:
        name: annihilator
        image: quay.io/financialtimes/annihilator
        published_ports:
          "80:80"
        env:
          SLEEP: 10
          CONSUL: "{{ ansible_default_ipv4.address }}:8500"

    - name: start monitoreador
      docker_container:
        name: monitoreador
        image: quay.io/financialtimes/monitoreador
        published_ports:
          "8000:8000"
        volumes:
          - /var/tmp/control:/var/tmp/control:ro
        env:
          SYSTEM_CODE: "{{ ipcode }}"
          SYSTEM_NAME: "flex-{{clusterid}}"
          SYSTEM_DESCRIPTION: "Physical host for flex {{clusterid}}"
          CONTROL_DIR: /var/tmp/control
          CONSUL_NODENAME: "{{ ansible_hostname }}"
          CONSUL_HTTP_ADDR: "{{ ansible_default_ipv4.address }}:8500"
