- hosts: localhost
  connection: local

  vars:
    ami: ami-c39604b0
    clusterid: infra
    description: 'Video Platform Shared Infrastructure'
    env: p
    environment_tag: default
    instance_type: m4.large
    ipcode: P386
    prefix: ftflex
    region: eu-west-1
    short_name: flex
    storage_instance_type: m3.medium
    system_code: 'Video-Platform'
    team_dl: videyo@ft.com

  tasks:
    - name: RDS Cluster
      shell: "aws rds create-db-cluster --db-cluster-identifier {{short_name}}-db-{{clusterid}}-{{env}}-cluster --engine aurora --master-username {{db_masterusername}} --master-user-password {{db_masterpassword}} --tags Key=name,Value={{short_name}}-db-{{clusterid}}-{{env}}-cluster Key=environment,Value={{env}} Key=ipCode,Value={{ipcode}} Key=systemCode,Value={{system_code}} Key=teamDl,Value={{team_dl}} Key=stopSchedule,Value=nostop --vpc-security-group-ids {{private_security_group_id}} --db-subnet-group-name private-subnets"
      ignore_errors: yes

    - name: RDS Instance
      shell: "aws rds create-db-instance --db-instance-identifier {{short_name}}-db-{{clusterid}}-{{env}}-cluster --engine aurora --db-cluster-identifier {{short_name}}-db-{{clusterid}}-{{env}}-cluster --db-instance-class db.r3.xlarge --tags Key=name,Value={{short_name}}-db-{{clusterid}}-{{env}}-cluster Key=environment,Value={{env}} Key=ipCode,Value={{ipcode}} Key=systemCode,Value={{system_code}} Key=teamDL,Value={{team_dl}} Key=stopSchedule,Value=nostop --db-subnet-group-name private-subnets"
      ignore_errors: yes

    - name: Build storage instance
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}01-law1a-eu-{{env}}"
        instance_type: "{{storage_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}01-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "storage"
          cluster: "{{clusterid}}"
          description: "{{description}} storage box"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: elasticsearch head one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}02-law1b-eu-{{env}}"
        instance_type: t2.small
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}02-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "elasticsearch"
          cluster: "{{clusterid}}"
          description: "{{description}} es head one"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: elasticsearch head two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}03-law1a-eu-{{env}}"
        instance_type: t2.small
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}03-law1a-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "elasticsearch"
          cluster: "{{clusterid}}"
          description: "{{description}} es head two"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: elasticsearch head three
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}04-law1b-eu-{{env}}"
        instance_type: t2.small
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}04-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "elasticsearch"
          cluster: "{{clusterid}}"
          description: "{{description}} es head three"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: mongodb config one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}05-law1b-eu-{{env}}"
        instance_type: t2.micro
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}05-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "mongo_config"
          cluster: "{{clusterid}}"
          description: "{{description}} mongodb config head"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: mongodb config two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}06-law1b-eu-{{env}}"
        instance_type: t2.micro
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}06-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "mongo_config"
          cluster: "{{clusterid}}"
          description: "{{description}} mongodb config head"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: mongodb config three
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}07-law1b-eu-{{env}}"
        instance_type: t2.micro
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}07-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "mongo_config"
          cluster: "{{clusterid}}"
          description: "{{description}} mongodb config head"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: mongodb router one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}08-law1b-eu-{{env}}"
        instance_type: t2.micro
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}08-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "mongo_router"
          cluster: "{{clusterid}}"
          description: "{{description}} mongodb router"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: mongodb router two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}09-law1b-eu-{{env}}"
        instance_type: t2.micro
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}09-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "mongo_router"
          cluster: "{{clusterid}}"
          description: "{{description}} mongodb router"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: mongodb shard one
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_0}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}10-law1b-eu-{{env}}"
        instance_type: t2.small
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}10-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "mongo_shard"
          cluster: "{{clusterid}}"
          description: "{{description}} mongodb shard"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh

    - name: mongodb shard two
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        key_name: "dios-mio"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_1}}"
        assign_public_ip: no
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{prefix}}{{clusterid}}11-law1b-eu-{{env}}"
        instance_type: t2.small
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "{{prefix}}{{clusterid}}11-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          flex_usage: "mongo_shard"
          cluster: "{{clusterid}}"
          description: "{{description}} mongodb shard"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh
