- hosts: storage
  become: yes

  tasks:
    - name: install nfs
      yum:
        name: nfs-utils
        state: latest

    - name: start nfs
      service:
        name: nfs
        state: started
        enabled: yes

- hosts:
  - elasticsearch
  become: yes
  tasks:
    - name: create es user
      user:
        name: elasticsearch

    - name: create es yum repo
      yum_repository:
        name: es
        description: es
        baseurl: https://packages.elastic.co/elasticsearch/1.7/centos
        gpgcheck: yes
        gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch

    - name: install es
      yum:
        name: elasticsearch
        state: latest

    - name: bump java
      yum:
        name: java-1.8.0
        state: latest

    - name: set java alternatives
      shell: alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java

    - name: add cluster hosts
      lineinfile:
        dest: /etc/elasticsearch/elasticsearch.yml
        line: "discovery.zen.ping.unicast.hosts: ['{{hostvars[groups['elasticsearch'][0]]['ansible_eth0']['ipv4']['address']}}', '{{hostvars[groups['elasticsearch'][1]]['ansible_eth0']['ipv4']['address']}}','{{hostvars[groups['elasticsearch'][2]]['ansible_eth0']['ipv4']['address']}}']"

    - name: set listen addr
      lineinfile:
        dest: /etc/elasticsearch/elasticsearch.yml
        line: "network.host: 0.0.0.0"

    - name: set listen addr
      lineinfile:
        dest: /etc/elasticsearch/elasticsearch.yml
        line: "discovery.zen.minimum_master_nodes: 2"

    - name: enable es
      service:
        name: elasticsearch
        state: started
        enabled: yes

- hosts:
  - mongo
  become: yes
  tasks:
    - name: mongo repo
      yum_repository:
        name: mongo
        description: mongo
        baseurl: https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.2/x86_64/
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-3.2.asc
    - name: install mongo
      yum:
        name: mongodb-org
        state: latest
    - name: enable mongo
      service:
        name: mongod
        state: started
        enabled: yes
