version: "2"

services:
  mio-base:
    image: hello-world
    extra_hosts:
      - consul:{{ consul_8500 }}
    environment:
      - SERVICE_IGNORE=true
      - SPRING_PROFILES_ACTIVE=server
      - HEAPSPACE=384m
      - APP_COMMAND_LINE=--spring.cloud.consul.discovery.prefer-agent-address=true
      - WAIT=15
      - APP_COMMAND_LINE=--hazelcast.publicIp={{ ansible_default_ipv4.address }}
    hostname:  {{ domain }}

  auth-service:
    image: registry.ooflex.net/flex-authentication-service #:6.2.397
    extends:
      service: mio-base
    ports:
      - "18101:18101"
      - 5701

  events-service:
    image: registry.ooflex.net/flex-events-service
    extends:
      service: mio-base
    ports:
      - "18113:18113"
      - 5701

  mam:
    image: registry.ooflex.net/flex-mam-app #:5.4.666
    extends:
      service: mio-base
    ports:
      - "18109:18109"
      - 5701

  searchelastic:
    image: registry.ooflex.net/flex-searchelastic-service #:1.0.357
    extends:
      service: mio-base
    ports:
      - "18119:18119"
      - 5701

  indexelastic:
    image: registry.ooflex.net/flex-indexelastic-service #:1.1.362
    extends:
      service: mio-base
    ports:
      - "18116:18116"
      - 5701

  metadatadesigner:
    image: registry.ooflex.net/flex-metadatadesigner-app #:1.0.54
    extends:
      service: mio-base
    environment:
      - SPRING_PROFILES_ACTIVE=server
      - HEAPSPACE=384m
      - APP_COMMAND_LINE=--spring.cloud.consul.discovery.prefer-agent-address=true
    ports:
      - "18120:18120"

  workflowdesigner:
    image: registry.ooflex.net/flex-workflowdesigner-app #:1.0.54
    extends:
      service: mio-base
    environment:
      - SPRING_PROFILES_ACTIVE=server
      - HEAPSPACE=384m
      - APP_COMMAND_LINE=--spring.cloud.consul.discovery.prefer-agent-address=true
    ports:
      - "18104:18104"

  master:
    image: registry.ooflex.net/flex-master
    environment:
      - APP_COMMAND_LINE=--hazelcast.publicIp={{ ansible_default_ipv4.address }}
      - IP={{ ansible_default_ipv4.address }}
      - WAIT=10
      - MIGRATE_DATABASE=yes #- will cause flyway to migrate the schema (instead of just validating)
    ports:
      - 20044:20044
      - 30044:30044
      - 9999:9999
      - 9990:9990
      - 7600:7600
      - 7801:7801
      - 57600:57600
      - 5445:5445
      - 4447:4447
      - 4712:4712
      - 5701:5701
    volumes:
      - /stuff/mio-enterprise/logs:/opt/jboss-eap-6.3/standalone/log
      - /stuff/mio-enterprise/storage:/flex/flex-enterprise/storage
    extra_hosts:
      - consul:{{ consul_8500 }}
    hostname: {{ domain }}
