#!/usr/bin/env bash
# chkconfig: 345 99 01
# description: some startup script


PID_FILE=/var/run/{{ app_name }}.pid
LOG_FILE=/var/log/{{ app_name }}.log

is_running() {
    [ -f "${PID_FILE}" ] && ps $(cat ${PID_FILE} ) &> /dev/null
}

case "$1" in
    start)
        if is_running; then
            echo "Already started"
        else
            echo "Starting {{app_name}}"

            {{ cmd }} & &> "${LOG_FILE}"
            echo $! > "${PID_FILE}"
            if ! is_running; then
                echo "Unable to start, see ${LOG_FILE}"
                exit 1
            fi
        fi
        ;;
    stop)
        if is_running; then
            echo -n "Stopping {{app_name}}"
            kill $(cat ${PID_FILE} )
            for i in {1..10}
            do
                if ! is_running; then
                    break
                fi

                echo -n "."
                sleep 1
            done
            echo

            if is_running; then
                echo "Not stopped; may still be shutting down or shutdown may have failed"
                exit 1
            else
                echo "Stopped"
                if [ -f "${PID_FILE}" ]; then
                    rm "${PID_FILE}"
                fi
            fi
        else
            echo "Not running"
        fi
        ;;
    restart)
        $0 stop
        if is_running; then
            echo "Unable to stop, will not attempt to start"
            exit 1
        fi
        $0 start
        ;;
    status)
        if is_running; then
            echo "Running"
        else
            echo "Stopped"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
