- hosts: localhost
  connection: local

  vars:
    region: eu-west-1
    ami: ami-c39604b0
    env: p
    ipcode: P386
    system_code: 'Video-Platform'
    description: 'Video Platform'
    team_dl: james.condron@ft.com
    environment_tag: default
    storage_instance_type: m3.medium
    instance_type: m3.large
    short_name: mio

  tasks:
    - name: Create buckets
      s3_bucket:
        name: "mio-{{item}}-{{clusterid}}"
        region: "{{region}}"
      with_items:
        - raw
        - edit
        - raw-proxy
        - edit-proxy
        - audio
        - web-video

    - name: RDS Cluster
      shell: "aws rds create-db-cluster --db-cluster-identifier mio-db-{{clusterid}}-cluster --engine aurora --master-username admin --master-user-password {{db_password}} --tags Key=name,Value=mio-db-{{clusterid}}-cluster Key=environment,Value={{env}} Key=ipCode,Value={{ipcode}} Key=systemCode,Value={{system_code}} Key=teamDl,Value={{team_dl}} Key=stopSchedule,Value=nostop"
      ignore_errors: yes

    - name: RDS Instance
      shell: "aws rds create-db-instance --db-instance-identifier mio-db-{{clusterid}}-host --engine aurora --db-cluster-identifier mio-db-{{clusterid}}-cluster --db-instance-class db.r3.xlarge --publicly-accessible --tags Key=name,Value=mio-db-{{clusterid}}-host Key=environment,Value={{env}} Key=ipCode,Value={{ipcode}} Key=systemCode,Value={{system_code}} Key=teamDL,Value={{team_dl}} Key=stopSchedule,Value=nostop"
      ignore_errors: yes

    - name: RAW Transcoder
      shell: "aws elastictranscoder create-pipeline --name mio-{{clusterid}}-transcoder --input-bucket mio-raw-{{clusterid}} --output-bucket mio-raw-proxy-{{clusterid}} --role {{role}}"
      ignore_errors: yes

    - name: Build storage instance
      ec2:
        image: "{{ami}}"
        region: "{{region}}"
        group_id:
          - "{{security_group_id}}"
          - "{{private_security_group_id}}"
        vpc_subnet_id: "{{private_subnet_2}}"
        assign_public_ip: no
        wait: true
        count: 1
        instance_type: "{{storage_instance_type}}"
        instance_profile_name: FT-Linux-Role
        instance_tags:
          Name: "ftmio{{clusterid}}01-law1b-eu-{{env}}"
          environment: "{{env}}"
          ipCode: "{{ipcode}}"
          systemCode: "{{system_code}}"
          teamDL: "{{team_dl}}"
          stopSchedule: "nostop"
          mio_usage: "storage"
          cluster: "{{clusterid}}"
          description: "{{description}} storage box"
        user_data: |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh
