  workflowdesigner:
    image: registry.ooflex.net/flex-workflowdesigner-app #:1.0.54
    extends:
      service: mio-base
    environment:
      - SPRING_PROFILES_ACTIVE=server
      - HEAPSPACE=384m
      - APP_COMMAND_LINE=--spring.cloud.consul.discovery.prefer-agent-address=true
    ports:
      - "18104:18104"

